### ISSUE TITLE
Timeout during deployment

### ISSUE THREAD

**Issue by noraj** [lucascaro/hexo-deployer-sftp#2]
Often the hexo deployment command randomly timeout before completing, so not all files are synced.

```json
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-deployer-sftp": "^0.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-njucks": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
```

Config:

```yaml
deploy:
- type: sftp
  host: x.x.x.x  
  user: xxx
  pass: xxx
  remotePath: /public/
  port: 22

```
